sources:
  - url: https://t.me/s/v2rayse
    tag: telegram
  - url: https://t.me/s/ShadowrocketNG
    tag: telegram
  - url: https://t.me/s/v2rayfree
    tag: telegram

  - url: https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/vless.txt
    tag: github
  - url: https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/vless.txt
    tag: github
  - url: https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/vless
    tag: github
  - url: https://raw.githubusercontent.com/Leon406/SubCrawler/master/subs/vless.txt
    tag: github
